SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[TotalVaccinatedPeople]
  FROM [PortfolioPj].[dbo].[PercentagePopulationsVaccinated]
